# .streamlit/secrets.toml

# Formato compatível com o código atual
SUPABASE_URL = "https://kbsurkwjqnpptgvaficy.supabase.co"
SUPABASE_KEY = "sb_publishable_DAySdd5M_qtExcZB-aigAA_7uR6xhGy"
APP_URL = "http://localhost:8501"
